spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MangaDataBase
    username: amor0009
    password: lukas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs